filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    json.ignore_decoding_error: true # <- add this
    scan_frequency: 5s
    tail_files: false
    ignore_older: 0

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
